/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_deadman_dh_model_generation_PerlinNoiseNative */

#ifndef _Included_com_deadman_dh_model_generation_PerlinNoiseNative
#define _Included_com_deadman_dh_model_generation_PerlinNoiseNative
#ifdef __cplusplus
extern "C" {
#endif
#undef com_deadman_dh_model_generation_PerlinNoiseNative_USE_NATIVE
#define com_deadman_dh_model_generation_PerlinNoiseNative_USE_NATIVE 1L
/*
 * Class:     com_deadman_dh_model_generation_PerlinNoiseNative
 * Method:    createPerlin
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_deadman_dh_model_generation_PerlinNoiseNative_createPerlin__
  (JNIEnv *, jclass);

/*
 * Class:     com_deadman_dh_model_generation_PerlinNoiseNative
 * Method:    createPerlin
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_deadman_dh_model_generation_PerlinNoiseNative_createPerlin__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_deadman_dh_model_generation_PerlinNoiseNative
 * Method:    deletePerlin
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_deadman_dh_model_generation_PerlinNoiseNative_deletePerlin
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_deadman_dh_model_generation_PerlinNoiseNative
 * Method:    perlinNoise1
 * Signature: (JD)D
 */
JNIEXPORT jdouble JNICALL Java_com_deadman_dh_model_generation_PerlinNoiseNative_perlinNoise1
  (JNIEnv *, jclass, jlong, jdouble);

/*
 * Class:     com_deadman_dh_model_generation_PerlinNoiseNative
 * Method:    perlinNoise2
 * Signature: (JDD)D
 */
JNIEXPORT jdouble JNICALL Java_com_deadman_dh_model_generation_PerlinNoiseNative_perlinNoise2
  (JNIEnv *, jclass, jlong, jdouble, jdouble);

/*
 * Class:     com_deadman_dh_model_generation_PerlinNoiseNative
 * Method:    perlinNoise3
 * Signature: (JDDD)D
 */
JNIEXPORT jdouble JNICALL Java_com_deadman_dh_model_generation_PerlinNoiseNative_perlinNoise3
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jdouble);

/*
 * Class:     com_deadman_dh_model_generation_PerlinNoiseNative
 * Method:    perlinTurbulence1
 * Signature: (JDD)D
 */
JNIEXPORT jdouble JNICALL Java_com_deadman_dh_model_generation_PerlinNoiseNative_perlinTurbulence1
  (JNIEnv *, jclass, jlong, jdouble, jdouble);

/*
 * Class:     com_deadman_dh_model_generation_PerlinNoiseNative
 * Method:    perlinTurbulence2
 * Signature: (JDDD)D
 */
JNIEXPORT jdouble JNICALL Java_com_deadman_dh_model_generation_PerlinNoiseNative_perlinTurbulence2
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jdouble);

/*
 * Class:     com_deadman_dh_model_generation_PerlinNoiseNative
 * Method:    perlinTurbulence3
 * Signature: (JDDDD)D
 */
JNIEXPORT jdouble JNICALL Java_com_deadman_dh_model_generation_PerlinNoiseNative_perlinTurbulence3
  (JNIEnv *, jclass, jlong, jdouble, jdouble, jdouble, jdouble);

/*
 * Class:     com_deadman_dh_model_generation_PerlinNoiseNative
 * Method:    perlinBuildMapTurbulence3
 * Signature: (J[[DDDDDDD)V
 */
JNIEXPORT void JNICALL Java_com_deadman_dh_model_generation_PerlinNoiseNative_perlinBuildMapTurbulence3
  (JNIEnv *, jclass, jlong, jobjectArray, jdouble, jdouble, jdouble, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
